print("silly line")
print("silly line")
# HANDYMAN_HOOK_POINT random-obscure-hook-point
print("silly line")
print("silly line")
print("silly line")
print("silly line")
print("silly line")
print("silly line")
print("silly line")
print("silly line")
